version: '3'
services:
  my-service:
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABSE=project
      - MYSQL_PORT=3306
    image: mmetharam/devops-lab:test1
